before_install: |
  git clone https://github.com/Shougo/vimproc.vim
  cd vimproc.vim
  make
language: ruby
rvm:
  - 2.2.2
sudo: false
cache: bundler
addons:
  apt:
    packages:
      - vim-gtk
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: xvfb-run rake ci
