sudo: required
dist: trusty
os:
  - osx
  - linux

language: ruby
rvm:
  - 2.2.2

cache:
  bundler: true
  directories:
    - $HOME/.rvm

install:
  - bash install_dependencies.sh
  - bundle install

addons:
  apt:
    packages:
      - vim-gtk
      - silversearcher-ag
      - ack-grep

before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then DISPLAY=:99.0 sh -e /etc/init.d/xvfb start; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok ) & fi
  - sleep 3 # give xvfb some time to start

script: rake ci
